language: python
python:
  - "3.6"      # current default Python on Travis CI
install:
  - pip install -r requirements.txt
  - pip install codecov
# command to run tests
script:
  - pytest
  - codecov
