language: python
python:
  - "3.6"      # current default Python on Travis CI
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
# command to run tests
script:
  - pytest --cov=./ --cov-report term-missing
  - codecov
